baseURL = "https://vodrazka.pl/"
languageCode = "en"
defaultContentLanguageInSubdir = true
defaultContentLanguage = "en"
theme = "anubis-custom"
disqusShortname = "vodrazka"
enableEmoji = true

[params]
author="Thomas Vodrazka"

[languages]
  [languages.en]
    languageName = "English"
    contentDir= "content/en"
    weight = 1
    title = "Thomas Vodrazka"
    subtitle = "Personal blog"
    readOtherPosts = "read other posts"
    menuMore = "more..."
    readMore = "more..."

    [languages.en.params.logo]
      logoText = "Thomas Vodrazka"
      logoHomeLink = "/"

[menu]
  [[menu.main]]
    identifier = "tech"
    name = "tech"
    url = "/tags/tech"
    weight = 1

  [[menu.main]]
    name = "books"
    url = "/tags/books"
    weight = 2

  [[menu.main]]
    name = "pictures"
    url = "/tags/pictures"
    weight = 3
